apiVersion: v1
kind: Pod
metadata:
  name: backend-pod
  labels:
    tier: database
  annotations: {
    "opencontrail.org/network" : '{"domain":"default-domain", "project": "demo-policy", "name":"backend-network"}'
  }
spec:
  containers:
    - name: backend-pod
      image: virtualhops/ato-ubuntu:latest
